[theme]
primaryColor="#4F2683" # Vikings Purple
backgroundColor="#0E1117" # Deep Dark Grey/Black
secondaryBackgroundColor="#262730" # Lighter Grey for sidebars/widgets
textColor="#FFFFFF" # White text
font="sans serif"